version: "3.8"
miduner_server:
  build: .
  dockerfile: ./docker/Dockerfile
  container_name: miduner_framework
  working_dir: /var/www/html
  port:
    - "9988:80"
  volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:etc/nginx/conf.d/app.conf
  link:
    - mysql

mysql:
  # image: nginx:alpine
  container_name: miduner_mysql
  port:
    - 33030:3306
  volumes:
    - ./docker/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password